# Generated by Django 3.2.5 on 2021-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210719_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participates',
            name='tags',
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
