# Generated by Django 3.2.5 on 2021-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210719_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_des', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
