# Generated by Django 3.2.5 on 2021-07-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210725_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participates',
            name='club',
        ),
        migrations.RemoveField(
            model_name='participates',
            name='name',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='participates',
        ),
    ]
